id: P010658
initial_creation_type: ocr
source_metadata:
  id: bdr:W29382
  title: གསུང་ཐོར་བུ། མཁས་གྲུབ་རྒྱ་མཚོ
  author: ''
  volumes:
    3fe9f3fbd12844169c3f97273e23a88a:
      image_group_id: I00KG04007
      title: ''
      volume_number: 1
      total_pages: 362
