id: P010658
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:35.021373
source_metadata:
  id: bdr:W29382
  title: གསུང་ཐོར་བུ། མཁས་གྲུབ་རྒྱ་མཚོ
  author: ''
  volumes:
    3fe9f3fbd12844169c3f97273e23a88a:
      image_group_id: I00KG04007
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
